export  const robots =[
    {
        id:1,
        name:'imam',
        username:'Imam',
        email:'imam@gmail.com'
    },
    {
        id:2,
        name:'boy',
        username:'Boy',
        email:'boy@gmail.com'
    },
    {
        id:3,
        name:'fritz',
        username:'Fritz',
        email:'email@gmail.com'
    },
    {
        id:4,
        name:'alif',
        username:'Alif',
        email:'alif@gmail.com'
    },
    {
        id:5,
        name:'mirza',
        username:'Mirza',
        email:'mirza@gmail.com'
    },
    {
        id:6,
        name:'daffa',
        username:'Daffa',
        email:'daffa@gmail.com'
    },
    {
        id:7,
        name:'fifah',
        username:'Fifah',
        email:'fifah@gmail.com'
    },
    {
        id:8,
        name:'rizal',
        username:'Rizal',
        email:'rizal@gmail.com'
    },
    {
        id:9,
        name:'bima',
        username:'Bima',
        email:'bima@gmail.com'
    },
    {
        id:10,
        name:'Nai',
        username:'nai',
        email:'nai@gmail.com'
    },
    {
        id:11,
        name:'aqsha',
        username:'Aqsha',
        email:'aqsha@gmail.com'
    },
]